meta_2/controllers/DiagramsController.php
<?php


namespace app\controllers;
use kartik\mpdf\Pdf;
use \Mpdf\Mpdf;

class DiagramsController extends \yii\web\Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }
    public function actionStudiesByYear()
    {
        return $this->render('studies-by-year');
    }
    public function actionSpeciesWordcloud()
    {
        return $this->render('species-wordcloud');
    }
    public function actionJournalWordcloud()
    {
        return $this->render('journal-wordcloud');
    }
    public function actionExperimentsPerStudy()
    {
        return $this->render('experiments-per-study');
    }
    public function actionTree()
    {
        return $this->render('tree');
    }
    public function actionWos()
    {
        return $this->render('wos');
    }
    public function actionHistoricalNetwork()
    {
        return $this->render('historical-network');
    }

	public function actionThematicMap()
    {
        return $this->render('thematic-map');
    }

	public function actionTopicNetwork()
    {
        return $this->render('topic-network');
    }

	public function actionCollaborationNetwork()
    {
        return $this->render('collaboration-network');
    }


    public function actionCollaborations()
    {
        $pdf = new mPDF();
        $pdf->WriteHTML('Hello World');

        $pdf->Output();

    }

}

meta_2/controllers/StudyInfoController.php
<?php

namespace app\controllers;

use Yii;
use app\models\StudyInfo;
use app\models\StudyInfoSearch;
use app\models\ExperimentsPerStudy;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
use app\models\CountryCodesOfFirstAuthors;


/**
 * StudyInfoController implements the CRUD actions for StudyInfo model.
 */
class StudyInfoController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all StudyInfo models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new StudyInfoSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    
    public function actionIndexYear($year)
    {
        $searchModel = new StudyInfoSearch();
        $searchModel->Year = $year;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);



        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    
    public function actionIndexExperiments($lower, $higher)
    {
        $higher = $higher - 1;
        $lower = $lower+1;
        $materials = ExperimentsPerStudy::find()->where('experiments = '. $lower )->all();
        $ids = [];
        foreach ($materials as $material) {
            array_push($ids, $material['study_id']);
        }

        $searchModel = new StudyInfoSearch();


        $query = StudyInfo::find();

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);


        $query->andFilterWhere(['in', 'study_ID', $ids]);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

	public function actionIndexFirstAuthorCountry($country)
    {
        $materials = CountryCodesOfFirstAuthors::find()->where('country_code = \''. $country. '\'')->all();
        $ids = [];
        foreach ($materials as $material) {
            array_push($ids, $material['study_id']);
        }

        $searchModel = new StudyInfoSearch();


        $query = StudyInfo::find();

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);


        $query->andFilterWhere(['in', 'study_ID', $ids]);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }





    /**
     * Displays a single StudyInfo model.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new StudyInfo model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new StudyInfo();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->study_ID]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing StudyInfo model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->study_ID]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing StudyInfo model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the StudyInfo model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return StudyInfo the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = StudyInfo::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

meta_2/views/diagrams/collaborations.php
<?php
/**
 * Created by PhpStorm.
 * User: gihan
 * Date: 16/01/18
 * Time: 10:49 AM
 */

use kartik\mpdf\Pdf;


echo 'Hello!';

?>

meta_2/views/diagrams/experiments-per-study.php
<head>
<style type="text/css">
 p.MsoNormal
	{margin-bottom:.0001pt;
	text-align:justify;
	text-justify:inter-ideograph;
	font-size:10.5pt;
	font-family:"Calibri",sans-serif;
	margin-left: 0cm;
	margin-right: 0cm;
	margin-top: 0cm;
}
.auto-style1 {
	font-size: large;
}
</style>
</head>

<h3 class="auto-style15">Histogram of Experiments per Study</h3>
<p class="MsoNormal">
<span style="font-family: &quot;Helvetica Neue&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #333333; background: white; mso-font-kerning: 0pt; mso-ansi-language: EN-AU; mso-fareast-language: EN-US" class="auto-style1">
Distribution of number of experiments per study in our data set.<o:p></o:p></span></p>
<p class="auto-style1">
<o:p><em>You can click on each bar to obtain the filtered list of corresponding 
studies.</em></o:p></p>
<p class="auto-style15">&nbsp;</p>

<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\grid\GridView;
use app\models\ExperimentsPerStudy;
use yii\data\ActiveDataProvider;

use miloschuman\highcharts\Highcharts;
use yii\web\JsExpression;



$this->title = 'Experiments per Study';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="countries-of-first-authors-index">
    <?php
    $studies = ExperimentsPerStudy::find()
        ->asArray()
        ->all();


    $i = 0;
    $hist_data=[];
    foreach ($studies as $study) {
        if (doubleval($study['experiments'] > 0)) {
            array_push($hist_data, floatval($study['experiments']));

            $i = $i + 1;
        }

    }
    
    
    
    $i = 0;
    $max = 0;
    foreach ($studies as $study) {
        if (doubleval($study['experiments']) > $max) {
            $max = doubleval($study['experiments']);
        }
        if (doubleval($study['experiments'] > 0)) {
            $temp_value = doubleval($study['experiments']);
            $hist_data[$i] = $temp_value;
            $i = $i + 1;
        }

    }

    for($x = 0; $x < $max; $x++) {
       $indices[$x] = $x+1;
    }


    $columns = array_fill(0, $max, 0);

    foreach ($hist_data as $hist_point) {
        $columns[$hist_point-1] = $columns[$hist_point-1] +1;
    }

    

    #print_r($hist_data);
    #print(count($subject_ids));



    ?>

    <?php



    $this->registerJsFile('https://code.highcharts.com/highcharts.js', [
        'depends' => 'miloschuman\highcharts\HighchartsAsset'
    ]);

    $this->registerJsFile('https://code.highcharts.com/modules/histogram-bellcurve.js', [
        'depends' => 'miloschuman\highcharts\HighchartsAsset'
    ]);


   // $hist_data = [3.5, 3, 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1];

    //print_r($hist_data);


//print_r($hist_data);


    ?>

    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/export-data.js"></script>

    <div id="container_2">
		<p class="MsoNormal">
		</p>
	</div>

    <script>

        hist_data = <?php echo json_encode($hist_data);?>;
        var data = [3.5, 3, 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3, 3, 4, 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3, 3.4, 3.5, 3.4, 3.2, 3.1, 3.4, 4.1, 4.2, 3.1, 3.2, 3.5, 3.6, 3, 3.4, 3.5, 2.3, 3.2, 3.5, 3.8, 3, 3.8, 3.2, 3.7, 3.3, 3.2, 3.2, 3.1, 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 2, 3, 2.2, 2.9, 2.9, 3.1, 3, 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, 2.8, 2.9, 3, 2.8, 3, 2.9, 2.6, 2.4, 2.4, 2.7, 2.7, 3, 3.4, 3.1, 2.3, 3, 2.5, 2.6, 3, 2.6, 2.3, 2.7, 3, 2.9, 2.9, 2.5, 2.8, 3.3, 2.7, 3, 2.9, 3, 3, 2.5, 2.9, 2.5, 3.6, 3.2, 2.7, 3, 2.5, 2.8, 3.2, 3, 3.8, 2.6, 2.2, 3.2, 2.8, 2.8, 2.7, 3.3, 3.2, 2.8, 3, 2.8, 3, 2.8, 3.8, 2.8, 2.8, 2.6, 3, 3.4, 3.1, 3, 3.1, 3.1, 3.1, 2.7, 3.2, 3.3, 3, 2.5, 3, 3.4, 3];

        Highcharts.chart('container', {
            title: {
                text: ''
            },
            plotOptions: {
            	column: {
                	pointPlacement: 'between'
            	}	
        	},

            legend: {
                enabled: false
            },
            xAxis: [{
                title: { text: 'Number of experiments' },
                alignTicks: false,
                tickInterval:1
            }, {
                title: { text: '' },
                alignTicks: false,
                opposite: true,
                tickInterval:1
            }],

            yAxis: [{
                title: { text: 'Number of Studies' }
            }, {
                title: { text: '' },
                opposite: true
            }],

            series: [{
                name: 'Histogram',
                type: 'histogram',
                xAxis: 0,
                yAxis: 0,
                baseSeries: 's1',
                zIndex: -1,
                dataLabels: {
                    enabled: true,
                    style: {
                        fontSize: '15px'
                    }
                },
                binWidth: 1,
                color: "#8a0022"
            }, {
                name: 'Data',
                type: 'scatter',
                xAxis: 1,
                yAxis: 1,
                data: hist_data,
                id: 's1',
                marker: {
                    radius: 1.5
                },
                visible: false
            }]
        });

    </script>


<script>

    x_data = <?php echo json_encode($indices);?>;
    y_data = <?php echo json_encode($columns);?>;
    var data = [3.5, 3, 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3, 3, 4, 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3, 3.4, 3.5, 3.4, 3.2, 3.1, 3.4, 4.1, 4.2, 3.1, 3.2, 3.5, 3.6, 3, 3.4, 3.5, 2.3, 3.2, 3.5, 3.8, 3, 3.8, 3.2, 3.7, 3.3, 3.2, 3.2, 3.1, 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 2, 3, 2.2, 2.9, 2.9, 3.1, 3, 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, 2.8, 2.9, 3, 2.8, 3, 2.9, 2.6, 2.4, 2.4, 2.7, 2.7, 3, 3.4, 3.1, 2.3, 3, 2.5, 2.6, 3, 2.6, 2.3, 2.7, 3, 2.9, 2.9, 2.5, 2.8, 3.3, 2.7, 3, 2.9, 3, 3, 2.5, 2.9, 2.5, 3.6, 3.2, 2.7, 3, 2.5, 2.8, 3.2, 3, 3.8, 2.6, 2.2, 3.2, 2.8, 2.8, 2.7, 3.3, 3.2, 2.8, 3, 2.8, 3, 2.8, 3.8, 2.8, 2.8, 2.6, 3, 3.4, 3.1, 3, 3.1, 3.1, 3.1, 2.7, 3.2, 3.3, 3, 2.5, 3, 3.4, 3];

    Highcharts.chart('container_2', {
        chart: {
            type: 'column'
        },
        title: {
            text: ''
        },
        xAxis: {
            categories: x_data,
            crosshair: true
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Number of studies'
            }
        },
        plotOptions: {
            column: {
                pointPadding: 0.0,
                pointWidth:20,
                borderWidth: 0
            }
        },
        series: [{
            name: 'Number of experiments',
            data: y_data,
            events: {
                click: function (event) {
                    var lower = event.point.x;
                    var url_to = <?php echo json_encode(Url::to(['study-info/index-experiments'])); ?>;
                    console.log(url_to);
                    var new_url = url_to.concat('&higher=', lower+1);
                    var new_url = new_url.concat('&lower=', lower);
                    var win = window.open(new_url, '_blank');
                    win.focus();
                    console.log(lower);
                    console.log(higher);
                }
            },
            binWidth:1,
            dataLabels: {
                enabled: true,
                step:0.5,
                style: {
                    fontSize: '15px'
                }
            },
            color: '#170555'


        }]
    });

</script>
</div>

meta_2/views/diagrams/historical-network.php
<head>
<style type="text/css">
 p.MsoNormal
	{margin-bottom:.0001pt;
	text-align:justify;
	text-justify:inter-ideograph;
	font-size:10.5pt;
	font-family:"Calibri",sans-serif;
	margin-left: 0cm;
	margin-right: 0cm;
	margin-top: 0cm;
}
.auto-style1 {
	font-size: large;
}
.auto-style2 {
	background-color: #FFFFFF;
}
</style>
</head>

<?php

use yii\helpers\Url;
use yii\helpers\Html;

$this->title = 'Historical network';
$this->params['breadcrumbs'][] = $this->title;
?>


    <h3><?= Html::encode($this->title) ?></h3>
    
    <p class="MsoNormal">
	<span class="auto-style1" style="font-family: &quot;Helvetica Neue&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #333333; background: white; mso-font-kerning: 0pt; mso-ansi-language: EN-AU; mso-fareast-language: EN-US">
	Historical publication network based on direct citation linkages of the included studies along the publication years (newest papers on top). The network was created using bibliometrix R-package and
	is based on bibliographic records from Web of Science for the 143 studies 
	included in our database.<o:p></o:p></span></p>
<br>
    
    <object data="Figure_hstorical_network_AI.pdf#toolbar=0&navpanes=0&scrollbar=0&view=FitH" type="application/pdf" width="1100" height="1080">
    <embed src="Figure_hstorical_network_AI.pdf#toolbar=0&navpanes=0&scrollbar=0&view=FitH" width="1100px" height="1080px" >
        <p>This browser does not support PDFs. Please download the PDF to view it: 
        <a href="Figure_hstorical_network_AI.pdf">Download PDF</a>.</p>
    </embed></object>  

meta_2/views/diagrams/index.php
<?php
/* @var $this yii\web\View */
?>
<h1>diagrams/index</h1>

<p>
    You may change the content of this page by modifying
    the file <code><?= __FILE__; ?></code>.
</p>

meta_2/views/diagrams/journal-wordcloud.php
<head>
<style type="text/css">
 p.MsoNormal
	{margin-bottom:.0001pt;
	text-align:justify;
	text-justify:inter-ideograph;
	font-size:10.5pt;
	font-family:"Calibri",sans-serif;
	margin-left: 0cm;
	margin-right: 0cm;
	margin-top: 0cm;
}
.auto-style1 {
	font-size: large;
}
</style>
</head>

<h3 class="auto-style15">Wordcloud of Journals<br></h3>

<p class="MsoNormal">
<span class="auto-style1" style="font-family: &quot;Helvetica Neue&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #333333; background: white; mso-font-kerning: 0pt; mso-ansi-language: EN-AU; mso-fareast-language: EN-US">
The word-cloud of the names of the journals where included studies were
published in. The sizes of the journal titles are proportional to the number of studies in
our database from a given journal.<o:p><br></o:p>
</span></p>
<p class="MsoNormal">
<o:p><br></o:p>
</p>
<p class="MsoNormal">
<o:p></o:p></p>

<?php

use yii\helpers\Html;
use yii\grid\GridView;
use app\models\Comparison;
use yii\data\ActiveDataProvider;

use miloschuman\highcharts\Highcharts;
use yii\web\JsExpression;



$this->title = 'Wordcloud of journals';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="countries-of-first-authors-index">
    <?php
    $comparisons = Comparison::find()
        ->asArray()
        ->groupBy(['Study_ID'])
        ->all();


    $i = 0;
    $words = "";
    foreach ($comparisons as $comparison) {

        $words = $words. ",". $comparison['Journal'];
        $i = $i + 1;


    }

    #$words = '\'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean bibendum erat ac justo sollicitudin, quis lacinia ligula fringilla. Pellentesque hendrerit, nisi vitae posuere condimentum, lectus urna accumsan libero, rutrum commodo mi lacus pretium erat. Phasellus pretium ultrices mi sed semper. Praesent ut tristique magna. Donec nisl tellus, sagittis ut tempus sit amet, consectetur eget erat. Sed ornare gravida lacinia. Curabitur iaculis metus purus, eget pretium est laoreet ut. Quisque tristique augue ac eros malesuada, vitae facilisis mauris sollicitudin. Mauris ac molestie nulla, vitae facilisis quam. Curabitur placerat ornare sem, in mattis purus posuere eget. Praesent non condimentum odio. Nunc aliquet, odio nec auctor congue, sapien justo dictum massa, nec fermentum massa sapien non tellus. Praesent luctus eros et nunc pretium hendrerit. In consequat et eros nec interdum. Ut neque dui, maximus id elit ac, consequat pretium tellus. Nullam vel accumsan lorem.\'';
    #print_r($words);
    #print(count($subject_ids));



    ?>

    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/wordcloud.js"></script>
    <div id="container"></div>
    <script>
        var text = "<?php echo $words ?>";

        var lines = text.split(/[,\.]+/g),
            data = Highcharts.reduce(lines, function (arr, word) {
                var obj = Highcharts.find(arr, function (obj) {
                    return obj.name === word;
                });
                if (obj) {
                    obj.weight += 1;
                } else {
                    obj = {
                        name: word,
                        weight: 1
                    };
                    arr.push(obj);
                }
                return arr;
            }, []);

        for (i = 0; i<data.length; i++) {
            data[i].weight = Math.log(data[i].weight);
        }
        Highcharts.chart('container', {
            chart: {
                borderWidth: 2
            },

            series: [{
                type: 'wordcloud',
                data: data,
                name: 'Occurrences',
                rotation: {
                    from: 0,
                    to: 0,
                    orientations: 2
                }
            }],
            title: {
                text: ''
            }
        });


    </script>


</div>

meta_2/views/diagrams/studies-by-year.php
<h3 class="auto-style15">Studies per year</h3>
<head>
    <meta content="en-au" http-equiv="Content-Language">
    <style type="text/css">
        p.MsoNormal
	{margin-bottom:.0001pt;
	text-align:justify;
	text-justify:inter-ideograph;
	font-size:10.5pt;
	font-family:"Calibri",sans-serif;
		margin-left: 0cm;
		margin-right: 0cm;
		margin-top: 0cm;
	}
	.auto-style16 {
		font-size: large;
	}
    </style>
</head>

<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\grid\GridView;
use app\models\StudiesByYear;
use yii\data\ActiveDataProvider;

use miloschuman\highcharts\Highcharts;
use yii\web\JsExpression;



$this->title = 'Studies Per Year';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="countries-of-first-authors-index">
	<p class="MsoNormal">
	<span class="auto-style16" style="font-family: &quot;Helvetica Neue&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #333333; background: white; mso-font-kerning: 0pt; mso-ansi-language: EN-AU; mso-fareast-language: EN-US">
	Number of included studies published per year. </span>&nbsp;</p>
	<p class="MsoNormal">
	<span class="auto-style16" style="font-family: &quot;Helvetica Neue&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #333333; background: white; mso-font-kerning: 0pt; mso-ansi-language: EN-AU; mso-fareast-language: EN-US">
	<em>You can click on each bar to 
	obtain the filtered list of corresponding review articles.</em><o:p><br></o:p>
	</span></p>
	<p class="MsoNormal">
	<o:p></o:p></p>

    <?php
    $years_view = StudiesByYear::find()
        ->asArray()
        ->all();

    $data_a =[];

    $i = 0;
    foreach ($years_view as $year_item) {
        if (doubleval($year_item['year'] > 0)) {
            $years[$i] = doubleval($year_item['year']);
            $i = $i + 1;
        }

    }

    $min_year = $years[0];
    $max_year = $years[sizeof($years)-1];
    $j = 0;
    for ($i = $min_year; $i<=$max_year; $i++) {
        $year_array[$j] = $i;


        $articles = StudiesByYear::find()
            ->select('studies')
            ->where(['year' => $i])
            ->asArray()
            ->all();

        if ($articles == null) {
            $article_array[$j] = 0;
        }
        else {
            $article_array[$j] = ($articles[0]['studies']);
        }
        array_push($data_a, [$year_array[$j], $article_array[$j]]);


        $article_array[$j] = doubleval($article_array[$j]);
        #$article_array[$j] = $articles;
        $j++;
    }

    #print_r($article_array);




    ?>

 


    
    
    <script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>

<div id="container" style="margin: 0pt auto; min-width: 310px; height: 400px;"></div>

<script>

    year_array = <?php echo json_encode($year_array);?>;
    article_array = <?php echo json_encode($article_array);?>;
   
    Highcharts.chart('container', {
        chart: {
            type: 'column',
            dataLabels: {
                enable: true
            }

        },
        title: {
            text: ''
        },
        xAxis: {
            categories: year_array,
            crosshair: true,
            title: {
                text: 'Year'
            }
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Number of studies'
            }
        },
        legend: {
            enabled: false
        },
        tooltip: {
            headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
            pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
            '<td style="padding:0"><b>{point.y}</b></td></tr>',
            footerFormat: '</table>',
            shared: true,
            useHTML: true
        },
        plotOptions: {
            column: {
                pointPadding: 0,
                borderWidth: 0,
                pointWidth: 12
            },
            series: {
                cursor: 'pointer',
                events: {
                    click: function (event) {
                        var year = event.point.category;
                        var url_to = <?php echo json_encode(Url::to(['study-info/index-year'])); ?>;
                        console.log(url_to);
                        var new_url = url_to.concat('&year=', year);
                       var win = window.open(new_url, '_blank');
                        win.focus();
                    }
                }

                
            }
        },
        series: [{
            name: ' ',
            data: article_array,
           
            dataLabels: {
                enable: true,
                
            },
            dataLabels: {
                enabled: true,
                
            },
            color:'#1b5838'

        }]
    });
</script>









</div>